name: flutter5
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  cached_network_image: ^3.4.1
  go_router: ^14.0.0
  get_it: ^8.2.0
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  sqflite: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.0.15
  drift: ^2.13.0
  sqflite_common_ffi: ^2.3.0
  json_annotation: ^4.9.0
  logger: ^2.0.0
  dio: ^5.4.0
  dio_http: ^5.0.4
  retrofit: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.4
  build_runner: ^2.10.1
  drift_dev: ^2.13.0
  json_serializable: ^6.7.1
  retrofit_generator: ^10.2.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true